#
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT weather_app.wsgi

beta_settings:
    cloud_sql_instances: weather-detector-app-335814:europe-west4:weather-instance1

runtime_config:
  python_version: 3